Refactor GitHub Actions workflow.
- Simplify Dockerfile by removing builder stage and instead opting to have the .jar produced via gradle outside the Dockerfile.
- Separate build and imaging into new jobs (`build-with-gradle`, `image-and-push`, `deploy-to-aks_staging`) with clear responsibilities.
- Add support for pull requests to the main branch.
- Improve readability, and ensure proper handling of artifacts.
- Refactor existing steps to be more modular and reusable.

diff --git a/.github/workflows/build-and-deploy.yaml b/.github/workflows/build-and-deploy.yaml
--- a/.github/workflows/build-and-deploy.yaml
+++ b/.github/workflows/build-and-deploy.yaml
@@ -7,32 +7,64 @@ env:
   REGISTRY: ghcr.io
 
 on:
+  pull_request:
+    branches:
+      - main
   workflow_dispatch: { }
 
 jobs:
-  build-and-push:
+  build-with-gradle:
     runs-on: ubuntu-latest
-    environment: "Actions Environment"
-    outputs:
-      image_path: ${{ steps.image-path.outputs.image_path }}
-      app_version: ${{ steps.app-version.outputs.app_version }}
+    timeout-minutes: 5
     permissions:
       contents: read
-      packages: write
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Read version from gradle.properties
-        id: app-version
-        run: |
-          VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2)
-          if [ -z "$VERSION" ]; then
-            echo "Error: Version not found in gradle.properties"; exit 1
-          fi
-          echo "app_version=$VERSION" >> $GITHUB_OUTPUT
-          echo "Detected project version: $VERSION"
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'corretto'
+          java-version: '21'
+
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+
+      - name: Execute Gradle build (with tests)
+        run: ./gradlew build
+
+      # save the built JAR as artifact for building Docker image, ensure success
+      - name: Upload JAR artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: app-jar
+          path: build/libs/litter.jar
+          if-no-files-found: error
+
+  image-and-push:
+    runs-on: ubuntu-latest
+    environment: "Actions Environment"
+    needs:
+      - build-with-gradle
+    permissions:
+      contents: read
+      packages: write
+    outputs:
+      image_path: ${{ steps.image-path.outputs.image_path }}
+      app_version: ${{ steps.app-version.outputs.app_version }}
+    timeout-minutes: 5
+
+    steps:
+      # checkout code for Dockerfile
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Download JAR artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: app-jar
 
       # image repo must be lowercase and GitHub Actions makes this difficult
       # see: https://github.com/orgs/community/discussions/10553
@@ -43,15 +75,22 @@ jobs:
           echo "image_path=$imagePath" >> $GITHUB_OUTPUT
           echo "Image path: $imagePath"
 
+      # read version from gradle.properties and append to output so it can be used later
+      - name: Read version from gradle.properties
+        id: app-version
+        run: |
+          VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
+          if [ -z "$VERSION" ]; then
+            echo "Error: Version not found in gradle.properties"; exit 1
+          fi
+          echo "app_version=$VERSION" >> $GITHUB_OUTPUT
+
       - name: Log into registry
         uses: docker/login-action@v3
         with:
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Set up Docker buildx
-        uses: docker/setup-buildx-action@v3
 
       - name: Extract Docker metadata
         id: meta
@@ -72,18 +111,19 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
 
-  deploy-to-aks:
-    needs: build-and-push
+  deploy-to-aks_staging:
     runs-on: ubuntu-latest
     environment: "Actions Environment"
+    needs:
+      - image-and-push
     permissions:
       actions: read
       contents: read
+    timeout-minutes: 5
 
     steps:
+      # checkout code for Helm chart
       - name: Git checkout
         uses: actions/checkout@v4
 
@@ -106,15 +146,12 @@ jobs:
           helmChart: ./chart/
           overrideFiles: ./chart/values.yaml
           overrides: |
-            app.image.repository: ${{ needs.build-and-push.outputs.image_path }}
+            app.image.repository: ${{ steps.image-path.outputs.image_path }}
             app.image.tag: ${{ github.sha }}
-            app.env.jwtSecret: ${{ secrets.JWT_SECRET }}
-            app.env.mongodbUri: ${{ secrets.MONGODB_URI }}
-            mongo.volume.csi.volumeHandle: ${{ secrets.MONGO_CSI_VOLUMEHANDLE }}
         id: bake
 
       - name: Validate generated manifests
-        uses: Azure/k8s-lint@v2.0
+        uses: Azure/k8s-lint@v3
         with:
           manifests: ${{ steps.bake.outputs.manifestsBundle }}
 
