CI/CD (GHA): Update workflows to handle build run ID and add artifact upload for pull requests/dispatch.

diff --git a/.github/workflows/cd_push-image.yml b/.github/workflows/cd_push-image.yml
--- a/.github/workflows/cd_push-image.yml
+++ b/.github/workflows/cd_push-image.yml
@@ -18,6 +18,7 @@ on:
 
 jobs:
   push-image:
+    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -32,17 +33,21 @@ jobs:
         id: determine-run
         run: |
           if [ "${{ github.event_name }}" = "workflow_run" ]; then
-            echo "BUILD_RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
+            echo "BUILD_RUN_ID=${{ github.event.workflow_run.id }}"
           elif [ -n "${{ github.event.inputs.build_run_id }}" ]; then
-            echo "BUILD_RUN_ID=${{ github.event.inputs.build_run_id }}" >> $GITHUB_OUTPUT
+            echo "BUILD_RUN_ID=${{ github.event.inputs.build_run_id }}"
+          else
+            echo "Error: No build run ID provided"; exit 1
           fi
+          echo "build_run_id=${BUILD_RUN_ID}" >> $GITHUB_OUTPUT
+          echo "Build run ID: $BUILD_RUN_ID"
 
       # Download the artifact using the download-artifact action
       - name: Download JAR Artifact from Build Workflow
         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
         with:
           name: litter-jar
-          run-id: ${{ steps.determine-run.outputs.BUILD_RUN_ID }}
+          run-id: ${{ steps.determine-run.outputs.build_run_id }}
           path: build/libs
 
       # Image repo must be lowercase and GitHub Actions doesn't have easy string manipulation.
